---
driver:
  name: docker
  binary: docker
  use_sudo: false

provisioner:
  name: chef_zero
  data_bags_path: test/integration/data_bags

platforms:
  - name: debian-7
  - name: debian-8

suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[python]
      - recipe[pentester]
    attributes:
      pentester:
        sn1per:
          packages: []
  - name: gitrob
    run_list:
      - recipe[apt]
      - recipe[postgresql::server]
      - recipe[pentester::gitrob_db]
      - recipe[pentester::gitrob]
    attributes:
      pentester:
        gitrob:
          use_db: true
          gh_auth_token: this-token-should-be-replaced-with-databag
          db:
            host: 127.0.0.1
            port: 5432
            db: gitrob
            user: gitrob
            pass: gitrob
