---
driver:
  name: docker
  binary: docker
  use_sudo: false

provisioner:
  name: chef_zero
  data_bags_path: test/integration/data_bags

platforms:
  - name: debian-7
  - name: debian-8

suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[python]
      - recipe[build-essential]
      - recipe[pentester]
      - recipe[pentester::w3af_src]
      - recipe[pentester::w3af_profiles]
    attributes:
      pentester:
        sn1per:
          packages: []
        w3af:
          profiles:
            kitchen:
              profile:
                name: kitchen
                description: Test profile for kitchen
              output.console:
                verbose: True
  - name: gitrob
    run_list:
      - recipe[apt]
      - recipe[postgresql::server]
      - recipe[pentester::gitrob_db]
      - recipe[pentester::gitrob_install]
      - recipe[pentester::gitrob_config]
    attributes:
      pentester:
        gitrob:
          use_db: true
          signatures:
            -
              part: filename
              type: match
              pattern: c99.php
              caption: "Oh F*ck** backdoor!"
              description: null
          gh_auth_token: this-token-should-be-replaced-with-databag
          db:
            host: 127.0.0.1
            port: 5432
            db: gitrob
            user: gitrob
            pass: gitrob
